import "./globals.css";
import Layout from "../layout/Layout";
import { Metadata } from "next/types";

//import { ContextProvider } from "@/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <ContextProvider> */}
        <Layout>{children}</Layout>
        {/* </ContextProvider> */}
      </body>
    </html>
  );
}
